# Generated by Django 4.2.7 on 2025-08-16 15:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Assessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assessor_name", models.CharField(blank=True, max_length=100)),
                ("assessor_email", models.EmailField(blank=True, max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("completed", "Completed"),
                            ("reviewed", "Reviewed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("overall_bias", models.CharField(blank=True, max_length=50)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="AssessmentTool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("rob2_parallel", "RoB 2 - Parallel Trial"),
                            ("rob2_cluster", "RoB 2 - Cluster Trial"),
                            ("rob2_crossover", "RoB 2 - Crossover Trial"),
                            ("robins_i", "ROBINS-I - Observational Studies"),
                            (
                                "robins_e",
                                "ROBINS-E - Observational Studies (Environmental)",
                            ),
                            ("amstar2", "AMSTAR-2 - Systematic Reviews"),
                            ("robis", "ROBIS - Systematic Reviews"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("display_name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("version", models.CharField(default="1.0", max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["display_name"],
            },
        ),
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("short_name", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("order", models.PositiveIntegerField(default=1)),
                ("is_overall", models.BooleanField(default=False)),
                (
                    "assessment_tool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="assessments.assessmenttool",
                    ),
                ),
            ],
            options={
                "ordering": ["assessment_tool", "order"],
                "unique_together": {("assessment_tool", "name")},
            },
        ),
        migrations.CreateModel(
            name="DomainAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bias_rating",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low risk"),
                            ("some_concerns", "Some concerns"),
                            ("high", "High risk"),
                            ("no_information", "No information"),
                        ],
                        max_length=20,
                    ),
                ),
                ("rationale", models.TextField(blank=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domain_assessments",
                        to="assessments.assessment",
                    ),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assessments.domain",
                    ),
                ),
            ],
            options={
                "unique_together": {("assessment", "domain")},
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("session_key", models.CharField(blank=True, max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Study",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("authors", models.CharField(blank=True, max_length=500)),
                ("journal", models.CharField(blank=True, max_length=200)),
                (
                    "year",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1900),
                            django.core.validators.MaxValueValidator(2100),
                        ],
                    ),
                ),
                ("doi", models.CharField(blank=True, max_length=100)),
                ("pmid", models.CharField(blank=True, max_length=20)),
                ("study_design", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="studies",
                        to="assessments.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "unique_together": {("project", "title")},
            },
        ),
        migrations.CreateModel(
            name="SignallingQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField()),
                ("order", models.PositiveIntegerField(default=1)),
                ("guidance", models.TextField(blank=True)),
                ("is_required", models.BooleanField(default=True)),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signalling_questions",
                        to="assessments.domain",
                    ),
                ),
            ],
            options={
                "ordering": ["domain", "order"],
                "unique_together": {("domain", "order")},
            },
        ),
        migrations.CreateModel(
            name="AssessmentExport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "export_type",
                    models.CharField(
                        choices=[("csv", "CSV"), ("plot", "Plot")], max_length=20
                    ),
                ),
                ("file_path", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exports",
                        to="assessments.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="assessment",
            name="assessment_tool",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="assessments.assessmenttool",
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="study",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assessments",
                to="assessments.study",
            ),
        ),
        migrations.CreateModel(
            name="QuestionResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "response",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("yes", "Yes"),
                            ("probably_yes", "Probably Yes"),
                            ("probably_no", "Probably No"),
                            ("no", "No"),
                            ("no_information", "No Information"),
                            ("not_applicable", "Not Applicable"),
                        ],
                        max_length=20,
                    ),
                ),
                ("justification", models.TextField(blank=True)),
                (
                    "domain_assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_responses",
                        to="assessments.domainassessment",
                    ),
                ),
                (
                    "signalling_question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assessments.signallingquestion",
                    ),
                ),
            ],
            options={
                "unique_together": {("domain_assessment", "signalling_question")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="assessment",
            unique_together={("study", "assessment_tool")},
        ),
    ]
