# Generated by Django 4.2.7 on 2025-08-17 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudyDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("full_text", "Full Text Article"),
                            ("protocol", "Study Protocol"),
                            ("supplementary", "Supplementary Material"),
                            ("registry", "Trial Registry Entry"),
                            ("other", "Other Document"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("file", models.FileField(upload_to="study_documents/%Y/%m/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("file_size", models.PositiveIntegerField(help_text="Size in bytes")),
                (
                    "extracted_text",
                    models.TextField(
                        blank=True,
                        help_text="Extracted text content for LLM processing",
                    ),
                ),
                (
                    "study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="assessments.study",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LLMModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=50)),
                ("model_name", models.CharField(max_length=100)),
                ("display_name", models.CharField(max_length=150)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "context_length",
                    models.PositiveIntegerField(
                        default=128000, help_text="Context window size in tokens"
                    ),
                ),
                (
                    "api_endpoint",
                    models.URLField(
                        blank=True, help_text="Custom API endpoint if needed"
                    ),
                ),
            ],
            options={
                "ordering": ["provider", "display_name"],
                "unique_together": {("provider", "model_name")},
            },
        ),
        migrations.CreateModel(
            name="LLMAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prompt_used", models.TextField()),
                ("raw_response", models.TextField()),
                ("parsed_results", models.JSONField()),
                (
                    "confidence_score",
                    models.FloatField(
                        blank=True,
                        help_text="LLM confidence in assessment (0-1)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "processing_time",
                    models.FloatField(
                        blank=True, help_text="Processing time in seconds", null=True
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error details if processing failed"
                    ),
                ),
                (
                    "assessment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="llm_assessment",
                        to="assessments.assessment",
                    ),
                ),
                (
                    "llm_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assessments.llmmodel",
                    ),
                ),
            ],
        ),
    ]
