# Generated by Django 4.2.7 on 2025-08-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0002_studydocument_llmmodel_llmassessment"),
    ]

    operations = [
        migrations.AddField(
            model_name="signallingquestion",
            name="explanation",
            field=models.TextField(
                blank=True,
                help_text="Detailed explanation of the question from the crib sheet",
            ),
        ),
    ]
